AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an S3 bucket and an EC2 instance in an existing VPC and subnet

Parameters:
  ExistingVPC:
    Type: AWS::EC2::VPC::Id
    Description: "Select an existing VPC"

  ExistingSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: "Select an existing Subnet"

  S3BucketName:
    Type: String
    Description: "Name of the S3 bucket"
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "^[a-z0-9.-]*$"
    ConstraintDescription: "Must be between 3 and 63 characters, and can contain lowercase letters, numbers, periods, and hyphens."

  LatestAmiId:
    Description: "Latest AMI"
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  InstanceType:
    Type: String
    Default: "t2.micro"

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH access"
      VpcId: !Ref ExistingVPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"  # Adjust as necessary for security

  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref ExistingSubnet

Outputs:
  S3BucketNameOutput:
    Description: "Name of the created S3 bucket"
    Value: !Ref MyS3Bucket

  EC2InstanceId:
    Description: "ID of the created EC2 instance"
    Value: !Ref MyEC2Instance

  VPCId:
    Description: "ID of the existing VPC"
    Value: !Ref ExistingVPC