Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: <name your bucket>

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0d06583a13678c938
      SubnetId: <subnet-id>  # Replace <subnet-id> with your specific Subnet ID
      SecurityGroupIds:      # Specify the security group IDs as a list
        - <sg-id>      